//package com.pm.billing_service.entity;
//
//import jakarta.persistence.Entity;
//import jakarta.persistence.GeneratedValue;
//import jakarta.persistence.GenerationType;
//import jakarta.persistence.Id;
//import lombok.Data;
//@Entity
//public class InvoiceItem {
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Long id;
//
//    private String description;
//    private int quantity;
//    private double price;
//
//    // Required by JPA
//    public InvoiceItem() {}
//
//    // With id (if you need to manually set it)
//    public InvoiceItem(Long id, String description, int quantity, double price) {
//        this.id = id;
//        this.description = description;
//        this.quantity = quantity;
//        this.price = price;
//    }
//
//    // ✅ Without id (for new items, id is generated by DB)
//    public InvoiceItem(String description, int quantity, double price) {
//        this.description = description;
//        this.quantity = quantity;
//        this.price = price;
//    }
//
//    // getters & setters
//}
